/* Real data — Antriana Panagi. Local images in assets/. */
var SITE = window.SITE = {
  name: "Antriana Panagi",
  role: "Graphic Designer",
  location: "Limassol, Cyprus",
  email: "antrianap10@gmail.com",
  phone: "+357 99 105091",
  linkedin: "https://www.linkedin.com/in/antriana-panagi-467b08314/",
  intro: "A practice built on grid-based precision and a genuine love for visual systems — confident without ever being loud.",
  bio: "Antriana Panagi is a Multimedia & Graphic Design graduate, holding a Bachelor's degree from the Cyprus University of Technology. Her work spans graphic design, social media and marketing coordination — grounded in analytical thinking and a deep respect for systems where every element earns its place.",
};

var SKILLS = window.SKILLS = ["Adobe Creative Suite", "Figma", "Canva", "Branding", "Typography", "Layout", "Art Direction", "Packaging", "Social Media", "Marketing"];

var EXPERIENCE = window.EXPERIENCE = [
  { yr: "2026 —", role: "Marketing Coordinator", org: "One Net", tag: "Current" },
  { yr: "2024 – 26", role: "Junior Marketing Coordinator", org: "One Net", tag: "Marketing" },
  { yr: "2024", role: "Designer · Social Media", org: "Think Positive", tag: "Design + Social" },
  { yr: "2023", role: "Graphic Designer", org: "Think Positive", tag: "Internship" },
  { yr: "2021 – 22", role: "Graphic Designer", org: "TEPAK · Limassol", tag: "Design" },
  { yr: "2020 – 24", role: "BA Multimedia & Graphic Design", org: "Cyprus University of Technology", tag: "Education" },
];

var gi = (d, n, e) => Array.from({ length: n }, (_, i) => `assets/${d}/${String(i + 1).padStart(2, '0')}.${e || 'jpg'}`);

var PROJECTS = window.PROJECTS = [
  {
    id: "social-media",
    title: "Social Media",
    cat: "Social Media",
    group: "editorial",
    year: "2026",
    span: 5,
    img: "assets/social-media/01.jpg",
    imgs: gi('social-media', 1),
    desc: "Social media content and campaign graphics for One Net Group — product launches, recruitment and brand awareness.",
    body: ["A suite of posts spanning multiple sub-brands: Abela Pulse, Abela IT, Abela.io and Sentrify.", "Each post balances brand consistency with content that stops the scroll."],
  },
  {
    id: "abela-pulse",
    title: "Abela Pulse",
    cat: "Event · Branding",
    group: "branding",
    year: "2025",
    span: 6,
    img: "assets/abela-pulse/02.jpg",
    imgs: gi('abela-pulse', 4),
    desc: "Event branding and collateral for the Abela Pulse launch party — One Net Group's product unveiling.",
    body: ["A full event identity across rollup banners, signage, screen graphics and branded merchandise.", "Dark, bold and kinetic — designed to match the energy of a product launch."],
  },
  {
    id: "navegistic",
    title: "Navegistic",
    cat: "Print · Exhibition",
    group: "editorial",
    year: "2025",
    span: 7,
    img: "assets/navegistic/03.jpg",
    imgs: gi('navegistic', 3),
    desc: "Exhibition stand and print campaign for One Net's World-Link + SES maritime satellite launch.",
    body: ["A full campaign package — brochure design and exhibition stand — built for a maritime trade show.", "Bold, clean layouts carrying technical content without losing the brand's confidence."],
  },
  {
    id: "my-brand",
    title: "My Brand",
    cat: "Brand Identity",
    group: "branding",
    year: "2024",
    span: 7, tall: true,
    img: "assets/my-brand.jpg",
    imgs: gi('my-brand', 1),
    desc: "A personal identity built around one hand-drawn, textured letter — the blue 'A' that holds this whole portfolio together.",
    body: ["The mark is deliberately tactile: grainy, organic, imperfect — a counterweight to the strict geometric type and grid it sits on.", "Electric blue does the talking. Everything else stays black, white and quiet so the work can breathe."],
  },
  {
    id: "platia",
    title: "Πλατεία Ηρωίδων",
    cat: "Editorial · Culture",
    group: "editorial",
    year: "2024",
    span: 5,
    img: "assets/platia.jpg",
    imgs: gi('platia', 12),
    desc: "An editorial and visual system for Heroines' Square — history, place and type meeting on the page.",
    body: ["A culturally-rooted project pairing photography with structured editorial layout.", "Greek and Latin typography share one grid without fighting for attention."],
  },
  {
    id: "shrubs-tea",
    title: "Shrubs Tea",
    cat: "Packaging",
    group: "packaging",
    year: "2023",
    span: 7, tall: true,
    img: "assets/shrubs-tea.png",
    imgs: gi('shrubs-tea', 5, 'png'),
    desc: "Brand and packaging for a botanical tea — natural, calm, shelf-ready.",
    body: ["A complete packaging system from logo to label, designed to sit confidently on a shelf.", "The Shrubs world stretches across product lines while staying recognisably one family."],
  },
  {
    id: "poker",
    title: "Ποκερ Σετ",
    cat: "Print · Product",
    group: "packaging",
    year: "2023",
    span: 6,
    img: "assets/poker.jpg",
    imgs: gi('poker', 3),
    desc: "Print and product design for a poker set — cards, box and all.",
    body: ["A playful product project balancing system and craft across many printed parts.", "Detail work: every card, edge and box panel considered."],
  },
];
