/* Real data — Antriana Panagi. Local images in assets/. */
var SITE = window.SITE = {
  name: "Antriana Panagi",
  role: "Graphic Designer",
  location: "Limassol, Cyprus",
  cv: "Resume - Antriana Panagi.pdf",
  email: "antrianap10@gmail.com",
  phone: "+357 99 105091",
  linkedin: "https://www.linkedin.com/in/antriana-panagi-467b08314/",
  intro: "Graphic design first, marketing end-to-end, built on grid-based precision and a genuine love for visual systems. Confident, never loud.",
  bio: "Antriana Panagi is a Multimedia & Graphic Design graduate (BA, Cyprus University of Technology) who works across the full creative-to-marketing pipeline, brand identity, editorial, packaging and motion, through to paid media, content strategy and lead generation. She turns complex, technical products into clear, catchy communication, grounded in analytical thinking and a deep respect for systems where every element earns its place.",
};

var SKILLS = window.SKILLS = ["Adobe Creative Suite", "Figma", "Canva", "Branding", "Typography", "Layout", "Art Direction", "Packaging", "Social Media", "Marketing", "Paid Media", "Lead Gen", "Content Strategy", "Email", "Analytics (GA4)", "Motion", "Web"];

var EXPERIENCE = window.EXPERIENCE = [
  { yr: "Mar 2026 – Present", role: "Marketing Coordinator", org: "One Net", note: "Promoted from Junior Marketing Coordinator (Oct 2024 – Mar 2026). Own marketing end-to-end for a maritime and enterprise-tech company, paid media, content, brand, web and reporting, as the sole marketer alongside the Group Marketing Manager." },
  { yr: "Feb – Jun 2024", role: "Graphic Designer & Social Media Coordinator", org: "Think Positive", note: "Brand, print and social content across formats, coordinating the social calendar to brief and deadline." },
  { yr: "Sep – Dec 2023", role: "Graphic Designer, Internship", org: "Think Positive", note: "Studio design production across print and digital deliverables." },
  { yr: "Oct 2021 – Aug 2022", role: "Graphic Designer", org: "TEPAK / Cyprus University of Technology", note: "Design for university departments and events, holding brand and grid consistency across every piece." },
  { yr: "Pre–One Net merger", role: "Brand & Print Projects", org: "WorldLink", note: "Delivered the Sierra Leone brand identity and the Navegistic print & exhibition projects before the company became One Net." },
];

var gi = (d, n, e) => Array.from({ length: n }, (_, i) => `assets/${d}/${String(i + 1).padStart(2, '0')}.${e || 'jpg'}`);

var PROJECTS = window.PROJECTS = [
  {
    id: "posidonia",
    title: "Posidonia Expo",
    cat: "Print | Exhibition | Motion | Social | Paid Media",
    group: "print",
    groups: ["print", "motion", "social"],
    year: "2026",
    span: 6,
    img: "assets/posidonia/IMG_1563.jpeg",
    imgs: [
      "assets/posidonia/IMG_1563.jpeg",
      "assets/posidonia/monitor%20final%20portait.mp4",
      "assets/posidonia/video%20wall%20final.mp4",
      "assets/posidonia/A6%20Leaflet%20in%20Hand%20Mockup.jpg",
      "assets/posidonia/posidonia%20social%20media.jpg",
    ],
    desc: "Booth graphics and print for Posidonia, one of the world's largest maritime trade shows, putting the new One Net brand on an international stage.",
    body: ["The show floor is loud and the audience knows the industry inside out, so the job was credibility, not noise. Antriana dressed the booth to read as authority without competing for attention: clean layouts, confident type and a system built to win new clients, sign partners and support the sales team's meetings.", "She designed the full visual world the booth ran on: the content for the LED wall and monitor, the leaflets, the gifts and the prize draw, all one consistent system. It was the first major public outing for the One Net identity, carrying the new brand into the maritime market the moment it mattered most."],
  },
  {
    id: "rebrand",
    title: "One Net Rebrand",
    cat: "Brand Identity | Web | Motion",
    group: "branding",
    groups: ["branding", "motion", "web"],
    year: "2026",
    span: 7,
    img: "assets/rebrand/stationery-mockup.jpg",
    imgs: [
      {src:"assets/one%20net%20website/Website%20Walkthrough.html", thumb:"assets/one%20net%20website/assets/walkthrough-thumb.png"},
      "assets/rebrand/Launch%20day%20final%20video%20final.mp4",
      "assets/rebrand/mockup.jpg",
      "assets/rebrand/Roll_up_Mockup.jpg",
      "assets/rebrand/door%20mockup.jpg",
      "assets/rebrand/flag%20mockup.jpg",
      "assets/rebrand/giftbox%20mockup.jpg",
    ],
    desc: "Four companies, one acquisition, one brand. A single identity for One Net, unifying WorldLink, Telaccount and One Novation across a global group operating in 8 hubs.",
    body: ["The brief was one line: rebrand the company. Antriana set the direction herself, deciding what the merged group should stand for and how much of each legacy brand to carry forward. The only fixed points were the One Net name and the hexagon kept from the previous mark. Everything else was hers to build.", "She rebuilt every material the company runs on: business cards, email signatures, presentation and social templates, signage, brochures and proposal docs. She art directed the new logo and wrote and produced the launch film from scratch, a sixty year story of four companies becoming one network. Today the identity is live across the whole group, all four companies operating as one."],
  },
  {
    id: "social-media",
    title: "Social Media",
    cat: "Social | Paid Media | Motion | Strategy",
    group: "social",
    groups: ["social", "motion"],
    year: "2026",
    span: 5,
    thumbStyle: { objectFit: "contain", background: "#ffffff" },
    img: "assets/social-media/Screenshot%202026-06-15%20141723.png",
    imgs: [
      "assets/social-media/social%20media-01-01.jpg",
      "assets/social-media/its%20an%20evolution.mp4",
      "assets/social-media/zwana%20nexus%20statistics.mp4",
      "assets/social-media/abela%20it%20tickets.mp4",
    ],
    desc: "Social content and campaign graphics for One Net across product launches, recruitment and brand awareness, spanning four sub brands.",
    body: ["Antriana sets the strategy and the monthly content calendar herself, then turns complex maritime and enterprise tech products into messaging that is clear, catchy and built to stop the scroll. Each post holds brand consistency across the group while doing a specific job.", "Behind the posts sits the paid engine. She plans and runs the campaigns across LinkedIn, Meta, Google (Search and Display) and X, writing the copy, designing the creative and setting the targeting and audience against an allocated budget. Leads are generated, qualified and handed to sales, then reported back to leadership each month."],
  },
  {
    id: "abela-pulse",
    title: "Abela Pulse",
    cat: "Event | Branding | Motion",
    group: "branding",
    groups: ["branding", "motion"],
    year: "2025",
    span: 6,
    img: "assets/abela-pulse/03.jpg",
    imgs: [
      "assets/abela-pulse/03.jpg",
      "assets/abela-pulse/abela%20pulse%20final.mp4",
      "assets/abela-pulse/abela%20pulse%20outside%20final.mp4",
      "assets/abela-pulse/01.jpg",
      "assets/abela-pulse/02.jpg",
      "assets/abela-pulse/04.jpg",
    ],
    desc: "Full event branding for the Abela Pulse launch party, One Net Group's flagship product unveiling to clients and partners.",
    body: ["Antriana set the visual direction herself: dark, bold and kinetic, built to match the energy of a launch that needed to land. The identity ran across the whole room, from animated visuals on the event screens to the entrance rollups and the branded gifts guests took home.", "Designed to make a product feel like an event, the work helped deliver one of the company's most successful launches to date, a night that drew strong attention from clients and partners and a notable flow of leads."],
  },
  {
    id: "navegistic",
    title: "Navegistic",
    cat: "Print | Exhibition | Motion",
    group: "print",
    groups: ["print", "motion"],
    year: "2025",
    span: 7,
    img: "assets/navegistic/03.jpg",
    imgs: gi('navegistic', 3),
    desc: "A co-branded stand and print campaign for WorldLink and SES at the Navegistic expo in Paraguay, two brands sharing one identity on the trade show floor.",
    body: ["The job was to make WorldLink and SES impossible to walk past while making them feel like one. Antriana built a single system that held both brands together, bold, clean and carrying heavy technical content without losing its footing, so two companies read as one confident presence on a competitive floor.", "She owned the whole stand: the structure itself, the presentation video on screen, the brochures, leaflets and gifts, all from one consistent design language. A complete exhibition package, designed from the ground up rather than dressed after the fact."],
  },
  {
    id: "sierra-leone",
    title: "Sierra Leone",
    cat: "Brand Identity | Web | Motion",
    group: "branding",
    groups: ["branding", "motion", "web"],
    year: "2025",
    span: 6,
    img: "assets/sierra-leone/SL%20video.mp4",
    imgs: [
      "assets/sierra-leone/SL%20video.mp4",
      {src:"assets/sierra-leone/Website%20Walkthrough.html"},
      "assets/sierra-leone/leaflet%20mockup.jpg",
      "assets/sierra-leone/roll%20up%20mockup.jpg",
      "assets/sierra-leone/roll%20up.jpg",
      "assets/sierra-leone/flag%20mockup4.jpg",
    ],
    desc: "A launch package for WorldLink's new office in Sierra Leone, marking the company's arrival in a new market.",
    body: ["Rather than build from scratch, Antriana adapted WorldLink's existing identity for the market, shifting the colour palette to suit Sierra Leone while keeping the brand recognisable. The system flexed to a new audience without losing what made it WorldLink: direct, confident and built to last.", "She produced the full launch set: the launch video, the rollups and leaflets for the opening, and a new website to give the office a home online. One adapted identity, carried cleanly across motion, print and digital."],
  },
  {
    id: "platia",
    title: "Πλατεία Ηρωίδων",
    cat: "Editorial | Culture",
    group: "editorial",
    year: "2024",
    span: 5,
    img: "assets/platia.jpg",
    imgs: [1,2,3,4,5,10,11,12].map(n => `assets/platia/${String(n).padStart(2,'0')}.jpg`),
    desc: "A booklet that renames Limassol's Heroes' Square as Heroines', reclaiming the stories of the women who lived there between 1990 and 1995.",
    body: ["The square is officially named for heroes. Antriana turned the name on itself, confronting how the women of that place and time were treated and labelled, and giving them back the recognition they were never given. The rename is the argument: one word that shifts whose story the square belongs to.", "Built from period newspapers and interviews she gathered herself, the booklet holds testimony, place and memory on a single grid, its Greek typography set to carry a heavy subject with restraint. It was made to last and to be passed on, so the story survives into a generation that would otherwise never hear it."],
  },
  {
    id: "poker",
    title: "Ποκερ Σετ",
    cat: "Print | Product",
    group: "print",
    year: "2023",
    span: 6,
    img: "assets/poker.jpg",
    imgs: gi('poker', 3),
    desc: "A poker set that turns the casino's own game against it, a tribute to the birds driven from the Akrotiri Salt Lake.",
    body: ["When Limassol's City of Dreams casino opened, it altered the flow of fresh water reaching Akrotiri, shifting the wetland from a winter lagoon to a summer swamp and displacing the species that once roosted there. Antriana answered with the casino's own object: a poker set that plays exactly as it should, while every card and chip carries a bird that no longer calls Aliki home. The game accuses the thing that built it; you play, and the artwork informs you as you do.", "Concept, research, illustration and build were all hers. She illustrated the birds, the cards and the chips by hand, then produced the set as a real object: laser cut chips and box, printed cards, a full deck made to be held. A university project carried from a real environmental story all the way to a finished, physical thing."],
  },
];
