/* Real data — Antriana Panagi. Local images in assets/. */
var SITE = window.SITE = {
  name: "Antriana Panagi",
  role: "Graphic Designer",
  location: "Limassol, Cyprus",
  email: "antrianap10@gmail.com",
  phone: "+357 99 105091",
  linkedin: "https://www.linkedin.com/in/antriana-panagi-467b08314/",
  intro: "Graphic design first, marketing end-to-end, built on grid-based precision and a genuine love for visual systems. Confident, never loud.",
  bio: "Antriana Panagi is a Multimedia & Graphic Design graduate (BA, Cyprus University of Technology) who works across the full creative-to-marketing pipeline — brand identity, editorial, packaging and motion, through to paid media, content strategy and lead generation. She turns complex, technical products into clear, catchy communication, grounded in analytical thinking and a deep respect for systems where every element earns its place.",
};

var SKILLS = window.SKILLS = ["Adobe Creative Suite", "Figma", "Canva", "Branding", "Typography", "Layout", "Art Direction", "Packaging", "Social Media", "Marketing"];

var EXPERIENCE = window.EXPERIENCE = [
  { yr: "2026 |", role: "Marketing Coordinator", org: "One Net", tag: "Current" },
  { yr: "2024 – 26", role: "Junior Marketing Coordinator", org: "One Net", tag: "Marketing" },
  { yr: "2024", role: "Designer · Social Media", org: "Think Positive", tag: "Design + Social" },
  { yr: "2023", role: "Graphic Designer", org: "Think Positive", tag: "Internship" },
  { yr: "2021 – 22", role: "Graphic Designer", org: "TEPAK · Limassol", tag: "Design" },
  { yr: "2020 – 24", role: "BA Multimedia & Graphic Design", org: "Cyprus University of Technology", tag: "Education" },
];

var gi = (d, n, e) => Array.from({ length: n }, (_, i) => `assets/${d}/${String(i + 1).padStart(2, '0')}.${e || 'jpg'}`);

var PROJECTS = window.PROJECTS = [
  {
    id: "rebrand",
    title: "One Net Rebrand",
    cat: "Brand Identity · Print",
    group: "branding",
    year: "2026",
    span: 7,
    img: "assets/rebrand/stationery-mockup.jpg",
    imgs: [
      {src:"assets/one net website/Website Walkthrough.html", thumb:"assets/one net website/assets/walkthrough-thumb.png"},
      "assets/rebrand/mockup.jpg",
      "assets/rebrand/Roll_up_Mockup.jpg",
      "assets/rebrand/Launch%20day%20final%20video%20final.mp4",
      "assets/rebrand/its%20an%20evolution.mp4",
    ],
    desc: "A full rebrand unifying One Net, WorldLink, Telaccount and One Novation under one coherent brand identity.",
    body: ["Four companies, one acquisition, one brand. The rebrand brought together One Net, WorldLink, Telaccount and One Novation under a single identity system spanning stationery, print and digital.", "From letterhead to launch video, every touchpoint designed to signal a new chapter without losing what each company stood for."],
  },
  {
    id: "social-media",
    title: "Social Media",
    cat: "Social · Paid Media · Strategy",
    group: "social",
    year: "2026",
    span: 5,
    role: "Strategy, design & paid media · Antriana Panagi",
    thumbStyle: { objectFit: "contain", background: "#ffffff" },
    img: "assets/social-media/Screenshot%202026-06-15%20141723.png",
    imgs: [
      "assets/social-media/social%20media-01-01.jpg",
      "assets/social-media/abela%20drive%20-%20file%20sync.mp4",
      "assets/social-media/zwana%20nexus%20statistics.mp4",
      "assets/social-media/abela%20it%20tickets.mp4",
    ],
    desc: "Social media content and campaign graphics for One Net, product launches, recruitment and brand awareness.",
    body: ["A suite of posts spanning multiple sub-brands: abela Pulse, abela IT, abela.io and Sentrify.", "Each post balances brand consistency with content that stops the scroll.", "Behind the posts sits the engine: I plan and run the paid campaigns across LinkedIn, Meta, Google (Search & Display) and X — copy, creative-to-budget, optimisation — and report the leads through to sales every month."],
  },
  {
    id: "abela-pulse",
    title: "Abela Pulse",
    cat: "Event · Branding",
    group: "branding",
    year: "2025",
    span: 6,
    img: "assets/abela-pulse/03.jpg",
    imgs: [
      "assets/abela-pulse/03.jpg",
      "assets/abela-pulse/abela%20pulse%20final.mp4",
      "assets/abela-pulse/abela%20pulse%20outside%20final.mp4",
      "assets/abela-pulse/01.jpg",
      "assets/abela-pulse/02.jpg",
      "assets/abela-pulse/04.jpg",
    ],
    desc: "Full event branding for the Abela Pulse launch party, One Net Group's flagship product unveiling.",
    body: ["A complete event identity spanning rollup banners, signage, screen graphics and branded merchandise.", "Dark, bold and kinetic, designed to match the energy of a product launch that demanded attention."],
  },
  {
    id: "posidonia",
    title: "Posidonia Expo",
    cat: "Print · Exhibition",
    group: "editorial",
    year: "2025",
    span: 6,
    img: "assets/posidonia/A6%20Leaflet%20in%20Hand%20Mockup.jpg",
    imgs: [
      "assets/posidonia/A6%20Leaflet%20in%20Hand%20Mockup.jpg",
      "assets/posidonia/IMG_1563.jpeg",
      "assets/posidonia/posidonia%20social%20media.jpg",
      "assets/posidonia/monitor%20final%20portait.mp4",
      "assets/posidonia/video%20wall%20final.mp4",
    ],
    desc: "Print collateral and exhibition presence for Posidonia, one of the world's largest maritime trade shows.",
    body: ["A leaflet and exhibition package built to represent WorldLink on an international stage, where every detail is seen by an audience that knows the industry inside out.", "Clean layouts, confident type and a system that communicates authority without competing for attention."],
  },
  {
    id: "navegistic",
    title: "Navegistic",
    cat: "Print · Exhibition",
    group: "editorial",
    year: "2025",
    span: 7,
    img: "assets/navegistic/03.jpg",
    imgs: gi('navegistic', 3),
    desc: "Exhibition stand and print campaign for WorldLink and SES, presented at the Navegistic expo in Paraguay.",
    body: ["A full campaign package, brochure design and exhibition stand, built to make WorldLink and SES impossible to walk past on the trade show floor.", "Bold, clean layouts carrying technical content without losing the brand's confidence."],
  },
  {
    id: "sierra-leone",
    title: "Sierra Leone",
    cat: "Brand Identity",
    group: "branding",
    year: "2025",
    span: 6,
    img: "assets/sierra-leone/SL%20video.mp4",
    imgs: [
      "assets/sierra-leone/SL%20video.mp4",
    ],
    desc: "A brand identity campaign for WorldLink's expansion into Sierra Leone — designed to build trust in a new market.",
    body: ["An identity built for clarity and confidence, created to introduce WorldLink's maritime connectivity services to Sierra Leone and establish presence from day one.", "The campaign travels across print and digital without losing its footing — recognisable, direct and built to last."],
  },
  {
    id: "platia",
    title: "Πλατεία Ηρωίδων",
    cat: "Editorial · Culture",
    group: "editorial",
    year: "2024",
    span: 5,
    img: "assets/platia.jpg",
    imgs: [1,2,3,4,5,10,11,12].map(n => `assets/platia/${String(n).padStart(2,'0')}.jpg`),
    desc: "A booklet about how women were treated in Heroes' Square, Limassol, renamed Heroines' Square to reclaim the stories of those subjected to violence and exploitation from 1990 to 1995.",
    body: ["The real square was called Heroes'. The booklet renames it Heroines', turning the lens on the women who lived there and how they were treated, giving them the recognition they were never given.", "Greek and Latin typography share one grid, holding testimony, place and memory together on the page."],
  },
  {
    id: "shrubs-tea",
    title: "Shrubs Tea",
    cat: "Packaging",
    group: "packaging",
    year: "2023",
    span: 7, tall: true,
    img: "assets/shrubs-tea.png",
    imgs: gi('shrubs-tea', 5, 'png'),
    desc: "Brand and packaging for a botanical tea, a fusion of elegance and practicality designed to captivate the senses from first glance.",
    body: ["A complete packaging system from logo to label, built to deliver an exceptional tea-drinking experience before a single cup is poured.", "The Shrubs world stretches across product lines while staying recognisably one family, shelf-ready and impossible to overlook."],
  },
  {
    id: "poker",
    title: "Ποκερ Σετ",
    cat: "Print · Product",
    group: "packaging",
    year: "2023",
    span: 6,
    img: "assets/poker.jpg",
    imgs: gi('poker', 3),
    desc: "A poker set designed around an environmental crisis, each card, chip and die a tribute to the birds driven from the Akrotiri Salt Lake.",
    body: ["The opening of Limassol's City of Dreams casino altered the flow of fresh water reaching Akrotiri, shifting the wetland from a winter lagoon to a summer swamp and displacing the species that once roosted there.", "48 poker chips, 12 dice and a full deck of cards, each illustrated with a bird that no longer calls Aliki home. A game that plays and informs at once."],
  },
];
